options:
  layer_type: 'base'
  name: 'rocky8-base'
  publish_tags: '8.9'
  pkg_manager: 'dnf'
  parent: 'scratch'
  publish_registry: 'internal.openchami.dev/boot-images/'

repos:
  - alias: 'Rock_BaseOS'
    url: 'https://download.rockylinux.org/pub/rocky/8/BaseOS/x86_64/os/'
    gpg: 'https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-8'
  - alias: 'Rock_AppStream'
    url: 'https://download.rockylinux.org/pub/rocky/8/AppStream/x86_64/os/'
    gpg: 'https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-8'
  - alias: 'Rock_PowerTools'
    url: 'https://dl.rockylinux.org/pub/rocky/8/PowerTools/x86_64/os'
    gpg: 'https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-Rocky-8'
  - alias: 'Epel'
    url: 'https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/'
    gpg: 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8'
  - alias: 'elrepo'
    url: 'http://elrepo.org/linux/elrepo/el8/x86_64/'
    gpg: 'https://www.elrepo.org/RPM-GPG-KEY-elrepo.org'

package_groups:
  - 'Minimal Install'
  - 'Development Tools'

packages:
  - kernel
  - wget
  - dracut-live
  - dmidecode
  - tpm2-tools
  - tpm2-abrmd
  - tpm2-tss
  - vim
  - curl
  - tmux
  - cloud-init
  - wireguard-tools
  - kmod-wireguard
  - jq

cmds:
  - cmd: 'dracut --add "dmsquash-live livenet network-manager" --kver $(basename /lib/modules/*) -N -f --logfile /tmp/dracut.log 2>/dev/null'
  - cmd: 'echo DRACUT LOG:; cat /tmp/dracut.log'