FROM docker.io/almalinux/8-minimal

# Install microdnf to enable package installation
RUN microdnf install -y \
        bash \
        buildah \
        python3.11 \
        python3.11-pip \
        fuse-overlayfs \
        tar \
        squashfs-tools \
        libcap && \
    python3.11 -m pip install --root-user-action=ignore --upgrade pip && \
    microdnf clean all

# Copy over the requirements file
COPY requirements.txt /tmp/requirements.txt

RUN python3.11 -m pip install --root-user-action=ignore --no-cache-dir --upgrade pip && \
    python3.11 -m pip install --root-user-action=ignore --no-cache-dir -r /tmp/requirements.txt && \
    rm -f /tmp/requirements.txt

# Add our custom scripts
COPY src/ /usr/local/bin/
RUN chmod -R 0755 /usr/local/bin/

# Allow non-root to run buildah commands
RUN setcap cap_setuid=ep "$(command -v newuidmap)" && \
    setcap cap_setgid=ep "$(command -v newgidmap)" && \
    chmod 0755 "$(command -v newuidmap)" && \
    chmod 0755 "$(command -v newgidmap)" && \
    echo "builder:2000:50000" > /etc/subuid && \
    echo "builder:2000:50000" > /etc/subgid

# Create local user for rootless image builds
RUN useradd --uid 1002 builder && \
    chown -R builder /home/builder

# Make builder the default user when running container
USER builder
WORKDIR /home/builder

# Set up environment variables
ENV BUILDAH_ISOLATION=chroot

# Default entrypoint
ENTRYPOINT ["/usr/bin/buildah", "unshare"]
